name: Fetch TTLock Unlock Records
on:
  schedule:
    - cron: '0 7 * * *'
  workflow_dispatch:
jobs:
  fetch_records:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          pip install requests
      - name: Run fetch_unlock_records.py
        run: |
          python fetch_unlock_records.py
